### ISSUE TITLE
revision 1613 fails to compile on Gentoo linux (2.6.30-gentoo-r4)

### ISSUE THREAD

**Issue by jbenden** [jbenden/aircrack-ng-migration#656]
**Reported by anonymous on 27 Jul 2009 03:32 UTC**

```
gcc -g -W -Wall -Werror -O3 -Wno-strict-aliasing -D_FILE_OFFSET_BITS=64 -D_REVISION=1613  -I/usr/local/include -DHAVE_SQLITE -Iinclude   -c -o airodump-ng.o airodump-ng.c
cc1: warnings being treated as errors
airodump-ng.c: In function 'dump_write_kismet_netxml':
airodump-ng.c:3474: error: ignoring return value of 'ftruncate', declared with attribute warn_unused_result
make[*** [airodump-ng.o](1]:) Error 1
make[Leaving directory `/home/user/Software/aircrack/aircrack-ng/src'
make: *** [all](1]:) Error 2
```

Migrated-From: https://trac.aircrack-ng.org/ticket/656

**Comment by jbenden** [comment]
**Comment by nhanth87 on 27 Jul 2009 03:32 UTC**

I meet this error too

**Comment by jbenden** [comment]
**Comment by anonymous on 27 Jul 2009 03:32 UTC**

I also have this error on Ubuntu 9.04

**Comment by jbenden** [comment]
**Modified by misterx on 27 Jul 2009 03:32 UTC**

**Comment by jbenden** [comment]
**Modified by misterx on 27 Jul 2009 03:32 UTC**

**Comment by jbenden** [comment]
**Comment by misterx on 27 Jul 2009 03:32 UTC**

Fixed in aircrack-ng/aircrack-ng@10f3fa3dc4ee63169423d3f365040c71e65d27ac.
